In [21]:
import sys
sys.version

'3.11.11 (main, Feb 12 2025, 15:06:01) [Clang 19.1.6 ]'

In [22]:
import torch
torch.__version__

'2.6.0'

In [23]:
x = torch.rand(5, 3)
x

tensor([[0.4957, 0.2814, 0.6490],
        [0.3440, 0.6418, 0.5305],
        [0.1626, 0.8292, 0.1251],
        [0.5812, 0.1803, 0.5021],
        [0.3954, 0.2301, 0.0092]])

In [24]:
torch.backends.mps.is_available()

True

In [25]:
torch.cuda.is_available()

False

In [26]:
if torch.backends.mps.is_available():
    device = torch.device('mps')
elif torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

device

device(type='mps')

In [27]:
x.to(device)

tensor([[0.4957, 0.2814, 0.6490],
        [0.3440, 0.6418, 0.5305],
        [0.1626, 0.8292, 0.1251],
        [0.5812, 0.1803, 0.5021],
        [0.3954, 0.2301, 0.0092]], device='mps:0')

In [28]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])