In [1]:
import sys
sys.version

'3.11.11 (main, Mar 11 2025, 17:28:32) [Clang 20.1.0 ]'

In [2]:
import torch
torch.__version__

'2.8.0.dev20250313+cu128'

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.6030, 0.9287, 0.6263],
        [0.3058, 0.5201, 0.3443],
        [0.4550, 0.0876, 0.9445],
        [0.1524, 0.5298, 0.2517],
        [0.9083, 0.7728, 0.3414]])

In [4]:
torch.backends.mps.is_available()

False

In [5]:
torch.cuda.is_available()

True

In [6]:
if torch.backends.mps.is_available():
    device = torch.device('mps')
elif torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

device

device(type='cuda')

In [7]:
x.to(device)

tensor([[0.6030, 0.9287, 0.6263],
        [0.3058, 0.5201, 0.3443],
        [0.4550, 0.0876, 0.9445],
        [0.1524, 0.5298, 0.2517],
        [0.9083, 0.7728, 0.3414]], device='cuda:0')

In [8]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])