In [1]:
import sys
sys.version

'3.11.11 (main, Feb 12 2025, 15:06:01) [Clang 19.1.6 ]'

In [2]:
import torch
torch.__version__

'2.6.0'

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.2962, 0.6458, 0.8317],
        [0.9506, 0.6967, 0.1935],
        [0.3282, 0.3084, 0.1249],
        [0.4071, 0.5973, 0.3023],
        [0.9250, 0.4557, 0.7156]])

In [4]:
torch.backends.mps.is_available()

True

In [5]:
torch.cuda.is_available()

False

In [6]:
if torch.backends.mps.is_available():
    device = torch.device('mps')
elif torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

device

device(type='mps')

In [7]:
x.to(device)

tensor([[0.2962, 0.6458, 0.8317],
        [0.9506, 0.6967, 0.1935],
        [0.3282, 0.3084, 0.1249],
        [0.4071, 0.5973, 0.3023],
        [0.9250, 0.4557, 0.7156]], device='mps:0')

In [8]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])